// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-ZI4CnCrXW0mkS_12Wbn9Wrq2UiQ3QDQ',
    appId: '1:281537451539:web:77085ba1ef1d53fa3d91e6',
    messagingSenderId: '281537451539',
    projectId: 'notes-b4b7c',
    authDomain: 'notes-b4b7c.firebaseapp.com',
    storageBucket: 'notes-b4b7c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEg4l7ZYN0V_FyMWjwpZ1J08VITGv4rmQ',
    appId: '1:281537451539:android:506db0553fcfbfd93d91e6',
    messagingSenderId: '281537451539',
    projectId: 'notes-b4b7c',
    storageBucket: 'notes-b4b7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiMbrqjIkblWqJv4QjDmVAdWAQG1_1UtY',
    appId: '1:281537451539:ios:a9ee7b502796ea623d91e6',
    messagingSenderId: '281537451539',
    projectId: 'notes-b4b7c',
    storageBucket: 'notes-b4b7c.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiMbrqjIkblWqJv4QjDmVAdWAQG1_1UtY',
    appId: '1:281537451539:ios:a9ee7b502796ea623d91e6',
    messagingSenderId: '281537451539',
    projectId: 'notes-b4b7c',
    storageBucket: 'notes-b4b7c.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-ZI4CnCrXW0mkS_12Wbn9Wrq2UiQ3QDQ',
    appId: '1:281537451539:web:baa2c1e03cdd260b3d91e6',
    messagingSenderId: '281537451539',
    projectId: 'notes-b4b7c',
    authDomain: 'notes-b4b7c.firebaseapp.com',
    storageBucket: 'notes-b4b7c.firebasestorage.app',
  );
}
